app:
  database:
    hostname: postgres-user
    port: 5432
  eureka:
    hostname: discovery-service
  keycloak:
    host: keycloak
  zipkin:
    hostname: zipkin
  inventory-service:
    hostname: inventory-service
  gateway-service:
    hostname: gateway-service
  kafka:
    hostname: kafka
    port: 29092

#spring:
#  profiles:
#    active: docker

logging:
  level:
    root: INFO
    com.eric6166: INFO
    org.hibernate.sql: DEBUG
    org.hibernate.type.descriptor.sql : TRACE
    org.apache.http: INFO