app:
  application-name: user # change
  server-port: 8086 # change
  application-version: v1
  context-path: api/${app.application-name}/${app.application-version}
  database-hostname: localhost # change
  database-port: 5436 # change
  database-name: ${app.application-name}_service_${app.application-version}
  eureka-hostname: localhost # change
  eureka-port: 8761
  keycloak-host: localhost # change
  keycloak-port: 8090
  api-gateway-hostname: localhost # change
  swagger-api-gateway-hostname: localhost # change
  api-gateway-server-port: 8181
  swagger-info-title: User Service # change
  swagger-info-version: v1.0 # change

security:
  enabled: true
  skip-urls:
    - /guest/**
    - /actuator/**
    - /swagger-ui/**
    - /v3/api-docs/**
    - /api-docs/**
    - /error/**
    - /auth/**

spring:
  application:
    name: ${app.application-name}-service
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://${app.keycloak-host}:${app.keycloak-port}/realms/spring-boot-microservices-realm
  datasource:
    url: jdbc:postgresql://${app.database-hostname}:${app.database-port}/${app.database-name}
    username: postgres
    password: secret
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
  flyway:
    baseline-on-migrate: true
    baseline-version: 0.0
    locations: classpath:db/migration/
    validate-on-migrate: true
    enabled: true
    table: schema_history

server:
  port: ${app.server-port}
  servlet:
    context-path: /${app.context-path}

keycloak:
  enabled: true
  realm: spring-boot-microservices-realm
  auth-server-url: http://${app.keycloak-host}:${app.keycloak-port}
  resource: microservices-admin-client
  credentials:
    secret: 123456789

eureka:
  client:
    serviceUrl:
      defaultZone: http://${app.eureka-hostname}:${app.eureka-port}/eureka
    registry-fetch-interval-seconds: 5
  instance:
    lease-renewal-interval-in-seconds: 5

logging:
  level:
    root: INFO
  pattern:
    level: "%5p[${spring.application.name:},%X{traceId:-},%X{spanId:-}]"

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /api-docs

swagger:
  server:
    url: http://${app.swagger-api-gateway-hostname}:${app.api-gateway-server-port}/${app.context-path}
  info:
    title: ${app.swagger-info-title}
    version: ${app.swagger-info-version}
    description: Documentation ${app.swagger-info-title} ${app.swagger-info-version}
#  security-scheme:
#    name: bearerAuth
#    bearer-format: JWT
#    scheme: bearer

#management:
#  tracing:
#    enabled: true
#    propagation:
#      type: b3
#    sampling:
#      probability: 1.0
#  health:
#    circuitbreakers:
#      enabled: true
#  endpoints:
#    web:
#      exposure:
#        include: "*"
#  endpoint:
#    health:
#      show-details: always
#  zipkin:
#    tracing:
#      endpoint: http://${app.zipkin-hostname}:${app.zipkin-server-port}/${app.zipkin-context-path}


management:
  endpoint:
    health:
      show-details: always
  health:
    diskspace:
      enabled: true
    db:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
