app:
  database-hostname: postgres-user
  database-port: 5432
  eureka-hostname: discovery-service
  keycloak-host: keycloak
  zipkin-hostname: zipkin
  inventory-service-hostname: inventory-service
  gateway-service-hostname: gateway-service